### ISSUE TITLE
Error in BonitaBPM 7.4.2 Community

### ISSUE THREAD

**Issue by rdiegoc** [Bonitasoft-Community/page_log#3]
Hi,
I download ad installed this page in BonitaBPM 7.4.2 Community Edition but I get an error when calling the page from an app.

![image](https://cloud.githubusercontent.com/assets/6864505/24468148/b1ae9976-148d-11e7-8a49-c0eff9689dfc.png)

Looking in the log... apparently it is a mistake in an import:
dex.groovy: 46: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 46, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;

This page is only available for SP?
Thanks

Complete error log
2017-03-29 14:39:51.424 -0300 WARNING: org.bonitasoft.console.common.server.page.CustomPageDependenciesResolver The custom page temporary lib directory C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\custompage_log1490807987210 cannot be deleted. This is likely to be due to a JDK bug on Windows. You can safely delete it after a server restart.
2017-03-29 14:39:52.410 -0300 WARNING: org.bonitasoft.livingapps.LivingApplicationPageServlet Error while trying to render the application page custompage_log
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 46: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 46, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 41: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 41, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:195)
	at org.bonitasoft.console.common.server.page.CustomPageService.registerPage(CustomPageService.java:128)
	at org.bonitasoft.console.common.server.page.PageRenderer.displayGroovyPage(PageRenderer.java:118)
	at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:77)
	at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:60)
	at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:147)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:130)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

2017-03-29 14:39:52.414 -0300 SEVERE: org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/bonita].[livingApplicationPageServlet] Servlet.service() for servlet [livingApplicationPageServlet] in context with path [/bonita] threw exception [startup failed:
C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 46: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 46, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 41: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 41, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

2 errors
] with root cause
javax.servlet.ServletException: startup failed:
C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 46: unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 @ line 46, column 1.
   import com.bonitasoft.engine.api.PlatformMonitoringAPI;
   ^

C:\app\BonitaBPMCommunity-7.4.2\workspace\tomcat\server\temp\bonita_portal_4956@rdiegoc\tenants\1\pages\custompage_log\Index.groovy: 41: unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 @ line 41, column 1.
   import com.bonitasoft.engine.api.TenantAPIAccessor;
   ^

2 errors

	at org.bonitasoft.livingapps.LivingApplicationPageServlet.handleException(LivingApplicationPageServlet.java:209)
	at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:147)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:130)
	at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by pierre-yves-monnet** [comment]
Hello,
Do you use the version 1.1 ? This one is for community.
I close the issue, feel free to reopen it if you have the error in 1.1

Thanks

**Comment by rdiegoc** [comment]
Hi,

Yes I do
I'm using version 1.1. Looking at the index.groovy code I see the import

![image](https://cloud.githubusercontent.com/assets/6864505/24508254/3e65755a-1539-11e7-9415-3a3205d32d5a.png)

the same error occurs in other pages: startcase (import com.bonitasoft.engine.api.TenantAPIAccessor;), bardigester (import com.bonitasoft.engine.bpm.bar.BusinessArchiveFactory;)

Regards
